MACHINE_USERNAME = "Red-GitHubBot"
REQUESTER = "jack1142/Red-GitHubBot"
REPO_NAME = "Red-DiscordBot"
FORK_REPO = f"{MACHINE_USERNAME}/{REPO_NAME}"
UPSTREAM_REPO = f"jack1142/{REPO_NAME}"
GIT_NAME = MACHINE_USERNAME
GIT_EMAIL = "87398303+red-githubbot[bot]@users.noreply.github.com"
MAINTENANCE_BRANCHES = {"3.4"}
