name: Build and deploy
on:
  push:
    branches:
      - main
  workflow_call:

concurrency: deploy-group

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    outputs:
      image_digest: ${{ steps.image-build.outputs.digest }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
          tags: |
            type=sha
            type=sha,format=long

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v7
        id: image-build
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  deploy:
    needs: build
    name: Deploy app
    runs-on: ubuntu-latest
    environment:
      name: red-githubbot
      url: https://red-githubbot.fly.dev
    steps:
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy app from newly built image
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          IMAGE_TO_DEPLOY: ghcr.io/${{ github.repository }}@${{ needs.build.outputs.image_digest }}
        run: flyctl deploy --app red-githubbot --image "$IMAGE_TO_DEPLOY"
